### ISSUE TITLE
[BUG] I tried using BitLinear in nanoRWKV but got the error.

### ISSUE THREAD

**Issue by win10ogod** [kyegomez/BitNet#16]
`https://github.com/BlinkDL/nanoRWKV/blob/master/model.py
`

I tried using BitLinear in nanoRWKV but got the error:
PS D:\nanoRWKV-master> python train.py
tokens per iteration will be: 491,520
Initializing a new model from scratch
defaulting to vocab_size of GPT-2 to 50304 (50257 rounded up for efficiency)
Traceback (most recent call last):
  File "D:\nanoRWKV-master\train.py", line 154, in <module>
    model = GPT(gptconf)
            ^^^^^^^^^^^^
  File "D:\nanoRWKV-master\model.py", line 210, in __init__
    h = nn.ModuleList([Block(config, i) for i in range(config.n_layer)]),
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\nanoRWKV-master\model.py", line 210, in <listcomp>
    h = nn.ModuleList([Block(config, i) for i in range(config.n_layer)]),
                       ^^^^^^^^^^^^^^^^
  File "D:\nanoRWKV-master\model.py", line 179, in __init__
    self.tmix = RWKV_TimeMix_x051a(config, layer_id)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\nanoRWKV-master\model.py", line 69, in __init__
    self.receptance = BitLinear(config.n_embd, config.n_embd, bias=config.bias)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BitLinear.__init__() got an unexpected keyword argument 'bias'

**Comment by kyegomez** [comment]
You're trying to add bias as a parameter but bit linear doesn't take that in

**Comment by win10ogod** [comment]
> 您試圖添加偏差作為參數，但位線性並沒有考慮它

Hello, how can I fix the error?
off topic: How can I use int8 or bit2 in training?

**Comment by kyegomez** [comment]
@win10ogod remove bias from the BitLinear()
