### ISSUE TITLE
[BUG] Google drive link in readme.md is dead

### ISSUE THREAD

**Issue by nathanielhudson** [kyegomez/BitNet#20]
**Describe the bug**
readme.md contains a link to https://drive.google.com/file/d/1gBuZRFBqMV3cVD902LXA_hmZl4e0dLyY/view which reports "Sorry, the file you have requested does not exist."

**To Reproduce**
Click on link :)

**Expected behavior**
Link would work

**Screenshots**
n/a

**Additional context**
n/a

**Comment by kyegomez** [comment]
@nathanielhudson we had the weights but the google drive link and the model was just bad. we must train the new verison
