### ISSUE TITLE
where to download bitnet model ?

### ISSUE THREAD

**Issue by dibu28** [kyegomez/BitNet#22]
**Describe the bug**
Where to download bitnet model? Which is shown in this example code:
```
bitnet.load_model("../model_checkpoint.pth")  # Download model
```

**To Reproduce**
Execute example. No model loaded.

**Expected behavior**
Link to download suitable model

**Comment by xeb** [comment]
Is there a plan to release the weights? Or is this a bug in loading them?

**Comment by dibu28** [comment]
> Is there a plan to release the weights? Or is this a bug in loading them?

I can't find where to download weights for the example and so I can't run example so I've created this bug.
As I understand only models trained for BitNet can be used and not any model.

**Comment by kyegomez** [comment]
@xeb @dibu28 we had the weights but the google drive link and the model was just bad. we must train the new verison

**Comment by dibu28** [comment]
> @xeb @dibu28 we had the weights but the google drive link and the model was just bad. we must train the new verison

Thank you! I will be waiting for the weights to test your new model.
