### ISSUE TITLE
ImportError: cannot import name 'BitLinear15bs' from 'bitnet.bitbnet_b158'[BUG] 

### ISSUE THREAD

**Issue by Bobby-youngking** [kyegomez/BitNet#34]
ImportError: cannot import name 'BitLinear15bs' from 'bitnet.bitbnet_b158'

**Comment by kyegomez** [comment]
@Bobby-youngking it's not in the __init__, still working on it!

**Comment by Bobby-youngking** [comment]
> @Bobby-youngking it's not in the **init**, still working on it!

but after i use this, the result is not limited to {-1, 0, 1},

**Comment by kyegomez** [comment]
@Bobby-youngking were still working on it!

**Comment by Bobby-youngking** [comment]
> @Bobby-youngking were still working on it!

does it mean that your code still need optimization?

**Comment by kyegomez** [comment]
@Bobby-youngking of course. all code will always need more optimization

**Comment by kyegomez** [comment]
@Bobby-youngking I have updatted it for `BitLinear`
