### ISSUE TITLE
forward method in Class BitLinear

### ISSUE THREAD

**Issue by guoqixin1** [kyegomez/BitNet#6]
hello, thanks for your Implementation. 
I was a bit confused while reading the bitnet/bitlinear.py forward()
as the paper shown:
<img width="256" alt="企业微信截图_09dcb834-cb93-4cd5-8d02-84d33f63a955" src="https://github.com/kyegomez/BitNet/assets/32630802/170b4d76-1e88-41e9-83ba-5a59408a0595">
i think the forward method should be:
<img width="525" alt="image" src="https://github.com/kyegomez/BitNet/assets/32630802/d834a913-1e85-416c-9019-96916cc6e68c">
did i misunderstand the process?

**Comment by kyegomez** [comment]
@guoqixin1 Hey thanks for pointing this out, we changed it yesterday so now there is a new verison let me know if you find any new issues
