### ISSUE TITLE
[BUG] cant compile the cuda

### ISSUE THREAD

**Issue by huynhducloi00** [kyegomez/BitNet#60]
build_pytorch/pytorch/.venv/lib/python3.12/site-packages/bitnet-1.1-py3.12-linux-x86_64.egg/gemm_lowbit_ext.cpython-312-x86_64-linux-gnu.so: undefined symbol: _ZNK2at10TensorBase8data_ptrI6__halfEEPT_v

have anyone seen that issue
i just try to run the example/kernel_test.py

**Comment by Dayun0925** [comment]
change the code "typedef half fp8" in gemm_lowbit_kernel.cu into "typedef at::Half fp8"
